package ru.poidem.intellij.plugins.ui;

import javax.swing.*;

/**
 * 09.11.2020
 *
 * @author SSalnikov
 */
public class PoidemPanel {
    private JPanel panel;
    private JCheckBox capitalizeTheNameOfCheckBox;
    private JCheckBox addGeneratedValueAnnotationsForAutoIncrementalSequences;
    private JCheckBox lombok;

    public PoidemPanel(PoidemSettings poidemSettings) {
        // Initialise l'interface graphique avec les settings qui ont été enregistrés avant
        capitalizeTheNameOfCheckBox.setSelected(poidemSettings.getCapitalize());
        addGeneratedValueAnnotationsForAutoIncrementalSequences.setSelected(poidemSettings.getAutoGenerated());
        lombok.setSelected(poidemSettings.getLombok());
    }

    public JPanel getPanel() {
        return panel;
    }

    public JCheckBox getCapitalizeTheNameOfCheckBox() {
        return capitalizeTheNameOfCheckBox;
    }

    public JCheckBox getAddGeneratedValueAnnotationsForAutoIncrementalSequences() {
        return addGeneratedValueAnnotationsForAutoIncrementalSequences;
    }

    public JCheckBox getLombok() {
        return lombok;
    }
}
