package ru.poidem.intellij.plugins.ui;

import com.intellij.openapi.components.PersistentStateComponent;
import com.intellij.openapi.components.State;
import com.intellij.openapi.components.Storage;
import com.intellij.util.xmlb.XmlSerializerUtil;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * 09.11.2020
 *
 * @author SSalnikov
 */
@State(
        name = "PoidemSettings",
        storages = {
                @Storage("PoidemSettings.xml")}
)
public class PoidemSettings implements PersistentStateComponent<PoidemSettings> {
    private Boolean capitalize;
    private Boolean autoGenerated;
    private Boolean lombok;

    public PoidemSettings() {
        capitalize = false;
        autoGenerated = false;
        lombok = false;
    }

    @Nullable
    @Override
    public PoidemSettings getState() {
        return this;
    }

    @Override
    public void loadState(@NotNull PoidemSettings state) {
        XmlSerializerUtil.copyBean(state, this);
    }

    public Boolean getCapitalize() {
        return capitalize;
    }

    public void setCapitalize(Boolean capitalize) {
        this.capitalize = capitalize;
    }

    public Boolean getAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(Boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public Boolean getLombok() {
        return lombok;
    }

    public void setLombok(Boolean lombok) {
        this.lombok = lombok;
    }
}
