package ru.poidem.intellij.plugins.ui;

import com.intellij.openapi.components.ServiceManager;
import com.intellij.openapi.options.Configurable;
import com.intellij.openapi.options.ConfigurationException;
import com.intellij.openapi.project.Project;
import org.jetbrains.annotations.Nls;
import org.jetbrains.annotations.Nullable;

import javax.swing.*;

/**
 * 09.11.2020
 *
 * @author SSalnikov
 */
public class PoidemConfigurable implements Configurable {
    private final PoidemSettings poidemSettings;
    private PoidemPanel poidemPanel;

    public PoidemConfigurable(Project project) {
        this.poidemSettings = ServiceManager.getService(project, PoidemSettings.class);
    }

    @Nls(capitalization = Nls.Capitalization.Title)
    @Override
    public String getDisplayName() {
        return "Poidem Generator";
    }

    @Nullable
    @Override
    public JComponent createComponent() {
        if (null == poidemPanel) {
            poidemPanel = new PoidemPanel(poidemSettings);
        }
        return poidemPanel.getPanel();
    }

    @Override
    public boolean isModified() {
        return (poidemPanel.getCapitalizeTheNameOfCheckBox().isSelected() != poidemSettings.getCapitalize()) ||
                (poidemPanel.getLombok().isSelected() != poidemSettings.getLombok()) ||
                (poidemPanel.getAddGeneratedValueAnnotationsForAutoIncrementalSequences().isSelected() != poidemSettings.getAutoGenerated());
    }

    @Override
    public void apply() throws ConfigurationException {
        poidemSettings.setCapitalize(poidemPanel.getCapitalizeTheNameOfCheckBox().isSelected());
        poidemSettings.setAutoGenerated(poidemPanel.getAddGeneratedValueAnnotationsForAutoIncrementalSequences().isSelected());
        poidemSettings.setLombok(poidemPanel.getLombok().isSelected());
    }
}
