package ru.poidem.intellij.plugins.action;

import com.intellij.database.psi.DbTable;
import com.intellij.openapi.actionSystem.AnActionEvent;
import com.intellij.psi.JavaDirectoryService;
import com.intellij.psi.PsiClass;
import com.intellij.psi.PsiDirectory;
import com.intellij.psi.PsiElement;
import icons.JavaUltimateIcons;
import org.apache.commons.lang3.StringUtils;
import org.jetbrains.annotations.NotNull;
import ru.poidem.intellij.plugins.ui.JPAMappingSettings;
import ru.poidem.intellij.plugins.ui.PoidemSettings;
import ru.poidem.intellij.plugins.util.Field;
import ru.poidem.intellij.plugins.util.TableInfo;

import java.util.*;

import static ru.poidem.intellij.plugins.util.Util.*;

/**
 * 09.11.2020
 *
 * @author SSalnikov
 */
public class Entity extends AbstractAction {

    @Override
    public void actionPerformed(AnActionEvent anActionEvent) {
        myActionPerformed(anActionEvent, DbTable.class);
    }

    @Override
    public void update(@NotNull AnActionEvent anActionEvent) {
        updateAction(anActionEvent, JavaUltimateIcons.Javaee.EntityBean);
        checkActionVisibility(anActionEvent, actionText);
        super.update(anActionEvent);
    }

    @Override
    public void fillAdditionalProperties(PsiElement psiElement, Map<String, String> additionalProperties, JPAMappingSettings jpaMappingSettings, PoidemSettings poidemSettings) {
        TableInfo tableInfo = new TableInfo((DbTable) psiElement);
        Set<Field> fields = getFields((DbTable) psiElement, jpaMappingSettings);
        StringBuilder importsField = new StringBuilder();
        Map<String,String> imports = new HashMap<>();
        for (Field field : fields) {
            if(StringUtils.isNotEmpty(field.getJavaImportType()) && !imports.containsKey(field.getJavaImportType()))
            {
                importsField.append("import ").append(field.getJavaImportType()).append(";").append("\n");
                imports.put(field.getJavaImportType(),"");
            }
        }

        additionalProperties.put("IMPORTS", importsField.toString());
        if(StringUtils.isNotBlank(tableInfo.getTableComment())) {
            additionalProperties.put("COMMENT", tableInfo.getTableComment());
        }
        String className = javaName(tableInfo.getTableName(), true);

        additionalProperties.put("SCHEMA", tableInfo.getTableSchema());
        additionalProperties.put("TABLE_NAME", tableInfo.getTableName().toUpperCase());

        for (Field field : fields) {
            if (field.getPrimary()) {
                if(!"ID".equals(field.getName())) {
                    additionalProperties.put("ID_NAME", field.getName());
                } else {
                    additionalProperties.put("ID_NAME", "");
                }
            }
        }

        StringBuilder columnFields = new StringBuilder();
        Map<String, String> comments = tableInfo.getColumsComment();
        for (Field field : fields) {
            if (!field.getPrimary()) {
                if(org.apache.commons.lang3.StringUtils.isNotEmpty(comments.get(field.getName()))) {
                    columnFields.append("    /**").append(comments.get(field.getName())).append("*/").append("\n");
                }
                if (poidemSettings.getAutoGenerated() && field.getAutoGenerated()) {
                    columnFields.append("    @GeneratedValue(strategy = GenerationType.IDENTITY)").append("\n");
                }
                if (poidemSettings.getCapitalize()) {
                    columnFields.append("    @Column(name = \"").append(field.getName().toUpperCase()).append("\"");
                    if (null != field.getColumnDefinition()) {
                        columnFields.append(", columnDefinition = \"");
                        columnFields.append(field.getColumnDefinition());
                        columnFields.append("\"");
                    }
                    columnFields.append(")").append("\n");
                } else {
                    columnFields.append("    @Column(name = \"").append(field.getName()).append("\"");
                    if (null != field.getColumnDefinition()) {
                        columnFields.append(", columnDefinition = \"");
                        columnFields.append(field.getColumnDefinition());
                        columnFields.append("\"");
                    }
                    columnFields.append(")").append("\n");
                }
                if(StringUtils.isNotEmpty((field.getJavaAnnotation()))){
                    columnFields.append("    ").append(field.getJavaAnnotation()).append("\n");
                }
                String javaType = field.getJavaType();
                columnFields.append("    private ").append(javaType).append(" ").append(javaName(field.getName(), false)).append(";").append("\n");
                columnFields.append("\n");
            }
        }
        additionalProperties.put("FIELDS", columnFields.toString());
    }

    @Override
    public List<PsiClass> loadTemplates(PsiElement psiElement, PsiDirectory psiDirectory, Map<String, String> additionalProperties, JPAMappingSettings jpaMappingSettings) {
        TableInfo tableInfo = new TableInfo((DbTable) psiElement);
        String className = javaName(tableInfo.getTableName(), true);
        List<PsiClass> psiClassList = new ArrayList<>();
        psiClassList.add(JavaDirectoryService.getInstance().createClass(psiDirectory, className, "PG_Entity.java", true, additionalProperties));
        return psiClassList;
    }
}
