package ru.poidem.intellij.plugins.util;

import com.intellij.database.model.DataType;

/**
 * 09.11.2020
 *
 * @author SSalnikov
 */
public class Field {
    private String name;
    private Boolean isAutoGenerated;
    private Boolean isPrimary;
    private DataType SQLType;
    private String javaType;
    private String javaImportType;
    private String javaAnnotation;
    private int scale;
    private String columnDefinition;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Boolean getAutoGenerated() {
        return isAutoGenerated;
    }

    public void setAutoGenerated(Boolean autoGenerated) {
        isAutoGenerated = autoGenerated;
    }

    public Boolean getPrimary() {
        return isPrimary;
    }

    public void setPrimary(Boolean primary) {
        isPrimary = primary;
    }

    public DataType getSQLType() {
        return SQLType;
    }

    public void setSQLType(DataType SQLType) {
        this.SQLType = SQLType;
    }

    public String getJavaType() {
        return javaType;
    }

    public void setJavaType(String javaType) {
        this.javaType = javaType;
    }

    public String getColumnDefinition() {
        return columnDefinition;
    }

    public void setColumnDefinition(String columnDefinition) {
        this.columnDefinition = columnDefinition;
    }

    public int getScale() {
        return scale;
    }

    public void setScale(int scale) {
        this.scale = scale;
    }

    public String getJavaImportType() {
        return javaImportType;
    }

    public void setJavaImportType(String javaImportType) {
        this.javaImportType = javaImportType;
    }

    public String getJavaAnnotation() {
        return javaAnnotation;
    }

    public void setJavaAnnotation(String javaAnnotation) {
        this.javaAnnotation = javaAnnotation;
    }
}
